(function(){
  "use strict";
  var cfg=window.GEOSANG_BOARD||{};
  var page=document.body.dataset.supportPage||"";
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c];});}
  function fmtDate(v){if(!v)return "";return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v));}
  function fmtSize(v){var n=Number(v||0);if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";return(n/1048576).toFixed(1)+" MB";}
  async function api(path,options){if(!cfg.functionUrl)throw new Error("게시판 연결 설정이 없습니다.");var res=await fetch(cfg.functionUrl+path,Object.assign({headers:{"Content-Type":"application/json",apikey:cfg.publishableKey}},options||{}));var data=await res.json().catch(function(){return{};});if(!res.ok||data.ok===false)throw new Error(data.error||"요청을 처리하지 못했습니다.");return data;}
  function state(el,title,desc,error){el.innerHTML='<div class="support-state'+(error?' support-error':'')+'"><strong>'+esc(title)+'</strong><span>'+esc(desc)+'</span></div>';}
  function resourceCard(item){return '<article class="support-card"><span class="support-card-tag">'+esc(item.category)+'</span><h2>'+esc(item.title)+'</h2><p>'+esc(item.excerpt)+'</p><div class="support-card-meta">'+esc(item.resource_version||"최신 자료")+'</div><a class="support-card-link" href="/support/resources/'+encodeURIComponent(item.slug)+'">무료 자료 받기 →</a></article>';}
  function noticeRow(item){return '<a class="support-row" href="/support/notices/'+encodeURIComponent(item.slug)+'"><span>'+esc(item.category)+'</span><h2>'+esc(item.title)+'</h2><time datetime="'+esc(item.published_at)+'">'+fmtDate(item.published_at)+'</time></a>';}
  async function initHome(){var n=document.getElementById("latestNotices"),r=document.getElementById("featuredResources");try{var both=await Promise.all([api("/notices?size=3"),api("/resources?size=3")]);n.innerHTML=both[0].items.length?both[0].items.map(noticeRow).join(""):"";if(!both[0].items.length)state(n,"등록된 공지가 없습니다","새 소식이 발행되면 이곳에 표시됩니다.");r.innerHTML=both[1].items.length?both[1].items.map(resourceCard).join(""):"";if(!both[1].items.length)state(r,"발행 준비 중입니다","실제 파일이 첨부되고 검토가 끝난 자료만 공개합니다.");}catch(e){state(n,"불러오지 못했습니다",e.message,true);state(r,"불러오지 못했습니다",e.message,true);}}
  async function initList(type){var list=document.getElementById("supportList"),form=document.getElementById("supportSearchForm"),input=document.getElementById("supportSearch");async function load(){state(list,"불러오는 중입니다","잠시만 기다려 주세요.");try{var data=await api("/"+type+"?size=30&q="+encodeURIComponent(input?input.value:""));list.innerHTML=data.items.length?data.items.map(type==="resources"?resourceCard:noticeRow).join(""):"";if(!data.items.length)state(list,"검색 결과가 없습니다",type==="resources"?"현재 발행된 자료가 없거나 검색어와 일치하는 자료가 없습니다.":"검색어와 일치하는 공지가 없습니다.");}catch(e){state(list,"목록을 불러오지 못했습니다",e.message,true);}}if(form)form.addEventListener("submit",function(e){e.preventDefault();load();});load();}
  async function initFaq(){var list=document.getElementById("faqList"),search=document.getElementById("faqSearch"),filters=document.getElementById("faqFilters"),items=[],category="전체";function draw(){var q=(search.value||"").trim().toLowerCase();var shown=items.filter(function(x){return(category==="전체"||x.category===category)&&(!q||(x.title+" "+x.body).toLowerCase().includes(q));});list.innerHTML=shown.map(function(x){return '<article class="support-faq"><button type="button" aria-expanded="false"><span>'+esc(x.category)+'</span><strong>'+esc(x.title)+'</strong><i>+</i></button><div class="answer">'+esc(x.body)+'</div></article>';}).join("");if(!shown.length)state(list,"검색 결과가 없습니다","다른 검색어를 입력해 보세요.");list.querySelectorAll(".support-faq button").forEach(function(btn){btn.addEventListener("click",function(){var item=btn.parentNode,open=item.classList.toggle("open");btn.setAttribute("aria-expanded",open?"true":"false");btn.querySelector("i").textContent=open?"−":"+";});});}
    api("/faqs?size=30").then(function(data){items=data.items;var cats=["전체"].concat(Array.from(new Set(items.map(function(x){return x.category;}))));filters.innerHTML=cats.map(function(c,i){return '<button class="faq-filter'+(i===0?' active':'')+'" type="button" data-category="'+esc(c)+'">'+esc(c)+'</button>';}).join("");filters.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;category=b.dataset.category;filters.querySelectorAll("button").forEach(function(x){x.classList.toggle("active",x===b);});draw();});search.addEventListener("input",draw);draw();}).catch(function(e){state(list,"FAQ를 불러오지 못했습니다",e.message,true);});}
  function slug(){var parts=location.pathname.split("/").filter(Boolean),last=parts[parts.length-1]||"";if(/\.html$/i.test(last))last="";return decodeURIComponent(last||new URLSearchParams(location.search).get("slug")||"");}
  async function initDetail(type){var root=document.getElementById("supportDetail");try{var data=await api("/"+type+"/"+encodeURIComponent(slug())),item=data.item;document.title=item.title+" | 거상마케팅센터";var isResource=type==="resources";var extras=isResource?'<div class="resource-info"><section class="resource-panel"><h2>이런 분께 권합니다</h2><ul>'+(item.target_audience||[]).map(function(x){return'<li>'+esc(x)+'</li>';}).join("")+'</ul></section><section class="resource-panel"><h2>활용 방법</h2><ul>'+(item.usage_steps||[]).map(function(x){return'<li>'+esc(x)+'</li>';}).join("")+'</ul></section></div><section class="resource-files"><h2>첨부파일</h2>'+((item.attachments||[]).length?item.attachments.map(function(f){return'<div class="resource-file"><div><strong>'+esc(f.original_name)+'</strong><br><small>'+esc(f.extension.toUpperCase())+' · '+fmtSize(f.size_bytes)+'</small></div></div>';}).join(""):'<div class="support-state"><strong>파일 준비 중</strong><span>실제 파일이 준비된 자료만 신청할 수 있습니다.</span></div>')+'</section>':'';
      root.innerHTML='<div class="support-breadcrumb"><a href="/">홈</a><span>›</span><a href="/support/'+type+'">'+(isResource?'무료 자료실':'공지사항')+'</a></div><article class="support-article"><header class="support-article-head"><span class="support-card-tag">'+esc(item.category)+'</span><h1>'+esc(item.title)+'</h1><p class="support-article-lead">'+esc(item.excerpt)+'</p><time>'+fmtDate(item.published_at||item.updated_at)+'</time></header><div class="support-article-body">'+esc(item.body)+'</div>'+extras+'<div class="support-article-actions">'+(isResource&&item.attachments.length?'<button class="support-button" type="button" id="openLeadForm">무료 자료 받기</button>':'')+(item.related_service_href?'<a class="support-button secondary" href="'+esc(item.related_service_href)+'">'+esc(item.related_service_label||"관련 서비스 보기")+'</a>':'')+'<a class="support-button secondary" href="/contact?type=consulting&source=support-'+(isResource?'resource':'notice')+'">상담문의</a></div></article>';
      if(isResource&&item.attachments.length)setupLead(item);
    }catch(e){state(root,"게시물을 열 수 없습니다",e.message,true);}}
  function setupLead(item){var dialog=document.getElementById("leadDialog"),form=document.getElementById("leadForm"),status=document.getElementById("leadStatus"),result=document.getElementById("downloadResult");document.getElementById("openLeadForm").addEventListener("click",function(){dialog.showModal();});document.getElementById("closeLeadForm").addEventListener("click",function(){dialog.close();});dialog.addEventListener("click",function(e){if(e.target===dialog)dialog.close();});form.addEventListener("submit",async function(e){e.preventDefault();var fd=new FormData(form),btn=form.querySelector("button[type=submit]"),key=crypto.randomUUID();btn.disabled=true;status.textContent="신청 정보를 저장하고 있습니다.";try{var data=await api("/resources/"+encodeURIComponent(item.slug)+"/request",{method:"POST",headers:{"Content-Type":"application/json",apikey:cfg.publishableKey,"x-idempotency-key":key},body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),company:fd.get("company"),interestedService:fd.get("interestedService"),privacyAgree:fd.get("privacyAgree")==="on",marketingAgree:fd.get("marketingAgree")==="on",website_hidden:fd.get("website_hidden"),source:"resource-detail",idempotencyKey:key,utmSource:new URLSearchParams(location.search).get("utm_source")||"",utmMedium:new URLSearchParams(location.search).get("utm_medium")||"",utmCampaign:new URLSearchParams(location.search).get("utm_campaign")||""})});status.textContent="";result.hidden=false;result.innerHTML='<strong>'+esc(data.message)+'</strong><div id="downloadLinks"></div><p class="lead-form-note">다운로드 링크는 10분 동안 사용할 수 있습니다.</p><a href="/contact?type=consulting&source=resource-download" class="support-button secondary">우리 업체 무료 진단받기</a>';var links=document.getElementById("downloadLinks");item.attachments.forEach(function(file){var b=document.createElement("button");b.type="button";b.className="support-button";b.textContent=file.original_name+" 다운로드";b.addEventListener("click",async function(){b.disabled=true;try{var out=await api("/downloads",{method:"POST",body:JSON.stringify({token:data.token,attachmentId:file.id})});window.location.assign(out.url);}catch(err){status.textContent=err.message;}finally{b.disabled=false;}});links.appendChild(b);});form.hidden=true;}catch(err){status.textContent=err.message;btn.disabled=false;}});}
  if(page==="home")initHome();else if(page==="notices")initList("notices");else if(page==="resources")initList("resources");else if(page==="faq")initFaq();else if(page==="notice-detail")initDetail("notices");else if(page==="resource-detail")initDetail("resources");
})();
